name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Depth 0 required for branch-based versioning
      - name: Update NuGet.config
        run: |
          dotnet nuget remove source defra
          dotnet nuget add source --username USERNAME --password "$GITHUB_TOKEN" --store-password-in-clear-text --name defra "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --configfile NuGet.config
      - name: Test
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0
      - name: Run unit tests
        run: |
          dotnet test --filter "Category!=IntegrationTests"
      - name: Run integration tests
        run: |
          docker compose up -d
          dotnet test --filter "Category=IntegrationTests"
      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  sonarcloud-scan:
    name: CDP SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    needs: build
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
